#!/bin/bash

function usage {
        cat <<EOM
     Usage: create_block -c <chainId> -n <networkid>
     Example: create_block -c 17835211 -n 178354
EOM
    exit 1
}

c=17835
n=17835

while getopts ":c:n:h" optKey; do
    case $optKey in
        c)
            c=$OPTARG
            ;;
        n)
            n=$OPTARG
            ;;
        h|*)
            usage
            ;;
    esac
done

# Check to see if the Genesis file exists.

if [ -f "/tmp/CustomGenesis.json" ]; then
        while true; do
        read -p "Genesis file already exists! Do you want to remove it?" yn
        case $yn in
            [Yy]* ) rm /tmp/CustomGenesis.json; break;;
            [Nn]* ) exit;;
            * ) echo "Yes or no.";;
     	esac
	done

else
cat <<EOF > /tmp/CustomGenesis.json
{
    "config": {
        "chainId": $c,
        "homesteadBlock": 0,
        "eip155Block": 0,
        "eip158Block": 0
    },
    "difficulty": "0x4000",
    "gasLimit": "0x2100000",
    "alloc": {}
}
EOF

fi

rm /tmp/static-nodes.json

for i in {1..3}; do
    count=$i
    # set the ip address for the enode
    nodeIP=10.$i.100.100

    # Create the node directory
    mkdir /home/appo/node$i

    # Load the CustomeGenesis file
    gubiq --datadir /home/appo/node$i init /tmp/CustomGenesis.json

    # Create a new account/wallet

    echo second >> /home/appo/node$i/passwd.file
    gubiq --password /home/appo/node$i/passwd.file account new >> /home/appo/node$i/wallet

    # Get the enode from console and drop out of console
    gubiq --rpc --datadir /home/appo/node$i/ --networkid $n console >& /tmp/node$i.output

    # Inject the IP Adress into the enode string
    enode=`cat /tmp/node$i.output | grep enode | awk '{print $5}'| sed "s/\[::\]/$nodeIP/g"`

# Write the enode info to the node directory
    echo $enode >> /home/appo/node$i/enode

# Create the static nodes file

if [ -f "/tmp/static-nodes.json" ]; then
## ------------------------------------#
cat >> /tmp/static-nodes.json <<EOL
"$enode",
EOL
## ------------------------------------#
else
## ------------------------------------#
echo "[" > /tmp/static-nodes.json
cat >> /tmp/static-nodes.json <<EOL
"$enode",
EOL
fi

done

# Close static nodes file
sed -i '$s/\",/\"/g' /tmp/static-nodes.json
echo "]" >> /tmp/static-nodes.json

# Copy static nodes to each node directory
one=1

cd /home/appo/
git clone https://github.com/ubiq/ubiq-net-intelligence-api.git

while [ "$one" -le "$count" ]; do
cp /tmp/static-nodes.json /home/appo/node$one && cp /home/appo/ubiq-net-intelligence-api /home/appo/node$one
(( one++ ))
done

e=1
# Copy datadir to each peer node
while [ $e -le 3 ]
do
        function expect_password {
        expect -c "\
         set timeout 90
         set env(TERM)
         spawn $1
         expect \"*password:\"
         send \"w@ntest\r\"
        expect eof
        "
        }

  expect_password "scp -p -o StrictHostKeyChecking=no -r /home/appo/node$e appo@node$e:/home/appo"

(( e++ ))
done